namespace Wizard.Enums
{
    public enum DIAG_HELPER_METHODS
    {
        RUN_SOLVENT_LEAK_TEST = 0,
        RUN_SYRINGE_EXCHANGE_UTILITY = 1,
        RESET_AUTOSAMPLER_SYRINGE_COUNT = 2,
        MOVE_ARM_AWAY_FROM_WASH_STATION = 3,
        RESET_WASH_PORT_SEPTUM_COUNT = 4,
        MOVE_ARM_HOME = 5,
        RUN_WASH_PORT_SEPTUM_LEAK_TEST = 6,
        CONFIRM_WASH_PORT_SEPTUM_POSITION = 7,
        RESET_INJECTION_PORT_SEPTUM_CONT = 8,
        CONFIRM_INJECTION_PORT_SEPTUM_POSITION = 9,
        RUN_SYRINGE_CELL_PATH_LEAK_TEST = 10,
        RESET_TEST_SYRINGE_COUNT = 11
    }
}